# Generated by Django 6.0.1 on 2026-01-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_blogpost_image_blogpost_is_announcement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='custom_title',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_anonymous_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
