# Generated by Django 6.0.1 on 2026-01-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_telegramuser_custom_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='admin_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
